### ISSUE TITLE
Not downloading all pictures from Reddit

### ISSUE THREAD

**Issue by ghost** [Jameak/ImageDownloader#2]
Hey,
I tried this software and tried your example with the wallpapers subreddit but instead of downloading 25 pictures, it only found/downloaded 4. Maybe some API has changed, do you care to check? Would love if the software was working again.

**Comment by Jameak** [comment]
Just tried it on the wallpapers-subreddit where it worked fine. Please try doing this and reporting back:
1. Restore the default settings, then restart the program.
2. Make sure that the field next to _IP-based Imgur API requests left of 500_ doesn't say zero.

If it still happens, could you attach a screenshot of the reddit-tab with the log visible after running it?
