### ISSUE TITLE
Program crashes

### ISSUE THREAD

**Issue by hockeyfreak** [Jameak/ImageDownloader#4]
Program crashes about halfway through download, then restarting it I can't get it to skip already downloaded files.  I'm downloading the same 300-400 images over and over.  Any way to fix? Why do you think it's crashing?
![croppercapture 1](https://user-images.githubusercontent.com/31639808/34013435-239d77ca-e0dd-11e7-8f10-67e068d7c470.jpg)

**Comment by Jameak** [comment]
Thank for you the report. I've identified the bug and released a fixed version.

It was caused by the program failing to figure out the aspect ratio of an image and then proceed to use the fallback value of zero which caused the program to attempt to divide by zero.

**Comment by hockeyfreak** [comment]
Thank you!!  Any way to make it not download images that have already been?

On Thu, Dec 14, 2017 at 4:46 PM, Marcus Quistgaard <notifications@github.com

**Comment by Jameak** [comment]
The intent for the "Custom query (Advanced)" option was to allow you to do precisely this by manually specifying some extra query parameters. Looking through the code today I suspect that this functionality is bugged for that specific use-case. I'll look into fixing it if I get the time.

For now you'll have to restart the download.
