### ISSUE TITLE
[Question] Imgur ID

### ISSUE THREAD

**Issue by shinji257** [Jameak/ImageDownloader#8]
I'm sorry but what is the Imgur ID that I can supply.  Can you point me in the right direction?

**Comment by Jameak** [comment]
The Imgur ID is the identifier that the program uses when contacting Imgur, which is how they apply rate-limits to our requests. The program has an imgur ID embedded for general use so you dont need to supply one.

However, if you expect to use the downloader heavily then switching to your own ID where you dont have to share the rate-limits with all the other users of the program is possible. To get your own ID do the following:
1. Login to Imgur
2. Go to this page: https://api.imgur.com/oauth2/addclient
3. Fill out the form.
   * For _Authorization type_ select _Anonymous usage without user authorization_.
   * The _Authorization callback URL_ must be filled out but isn't used by the program.
   * Fill out the rest as desired.
4. Copy the resulting client id (not the client secret)
5. Paste the id into the Imgur ID box and press _Save settings_
6. Then restart the program.

If you forget the client id or want to delete it from your account, see this page: https://imgur.com/account/settings/apps

**Comment by shinji257** [comment]
Ok.  Thank you.  I thought that is what it was but for some reason it was telling me it was invalid before.  Looks like it is working now.  Thanks for clarifying.
