### ISSUE TITLE
App downloads 3 .jpg of the same picture 

### ISSUE THREAD

**Issue by Minibus93** [Jameak/ImageDownloader#9]
Just discovered this amazing project, tested it and output is that every picture of the subreddit I downloaded is downloaded with 2 more copies than needed.
Basically for every pic on the subreddit I get, as output, something like this:

Original file name.jpg
Original file name(1).jpg
Original file name(2).jpg

It's boring to have to delete manually all of the (1) and (2)

**Comment by Jameak** [comment]
I've tried running the program on a variety of subreddits containing both albums and direct image links and have been unable to reproduce your issue.

Could you provide the following:
- A subreddit where the issue occurs.
- An image of the settings that you're using from both the 'Reddit' tab and the 'Settings' tab.
- An attached text-file or a pastebin-link containing the log that ImageDownloader creates when you press 'Show Log' after having downloaded images from the subreddit where the issue occurs.

**Comment by Minibus93** [comment]
Hi! The subreddit I tried was r/Animewallpaper, but since you couldn't reproduce the issue I re-try to download from there and it went all fine, no duplicates! 

I re-tried just to be sure and no duplicate again I don't know what happened, but now it's working fine

I'll consider this resolved, thanks for the very useful project!
